# Generated by Django 2.2.5 on 2019-12-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191203_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
